"""Container for data, masks, graphics items, annotations logic etc. pp.
related to a single, identifyable thingy in an image stack
"""

class Entity():
    """Base entity derived from image
    should be generated by factory only

    Will be hirachically ordered. Thus might not
    have any functions that prevent an atomic use
    of the entities e.g. as nodes in an hirachical,
    ordered tree
    """

    _used_ids = set([])

    def __init__(self, entity_id):
        """raises valueerror if entity_id is not none
        and invalid id because
        """

        ### Logic ###
        # must be unique, enforced on factory level
        # on factory level to avoid resetting state of
        # class later on
        self.eid = entity_id

        ### Imagepixel context ###
        # properties of the entity context of
        # pixel based images / sources of data
        # a numpy slice than can be used to get the pixels
        # from the image that belong to the object in each
        # respective channel
        self._slice = (None, None)
        # boolean numpy mask
        # must have same shape as the _slice. Given the of
        # the image returned after slicing, the pixel in the
        # mask being True signify pixels within the slice
        # beeing image pixels
        self._mask = None

        ### View context ###
        # properties of the entity in context of
        # the view of the entity
        # a QRect locating the entity in the scene it is
        # placed in
        self._boundingbox = None
        # QPolygon, giving the polygon of the entity
        # representing it in the view
        self._polygons = None

        ### Common Attributes ###
        # all attributes relevant for drawing
        # like colors, shapes, whatever
        # to be manipulated directly
        self.attributes = {}

        ### Data ###
        # all the stuff that is data related
        # like annotation and derived values/scalars
        # can be manipulated directly
        self.tags = []
        self.scalars = {}

    def set_mask(self, points):
        """Sets the mask, given the polygon
        points:
        list of numpy.arrays with the shape (n, 2),
        where each index i is on point in the polygon
        """
        pass

    def set_polygon(self, mask, eslice):
        """Sets the polygon, given the bool mask for the eslice
        where bool mask is a np.array and eslice a tupple of slices
        """
        pass
