"""Generates and manages objects
objects contain
"""

class Entity():
    """Base entity derived from image
    should be generated by factory only
    """
    def __init__(self, entity_id):
        self.entity_id = entity_id
 
        # anchor coordinates in image
        self._anchor = None
        # slices that gives the entity from mask
        self._slice = None

        # boolean numpy mask seperates pixels belonging
        # to entity from pixel belonging to background
        # within bounding box
        self._mask = None
        
        # boundingbox within sceene
        self._boundingbox = None

        # polgon for drawing using pyqt rendere
        self._polygons = None
        
        # all attributes relevant for drawing
        # like colors
        self._drawing_attributes = {}
